"""phase 6 etymology and sample texts

Revision ID: 3533723938bd
Revises: 18a4634fbdbc
Create Date: 2026-06-15 21:37:12.052298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3533723938bd'
down_revision = '18a4634fbdbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etymology_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('dialect_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('article_type', sa.Enum('history', 'dialect', 'vocabulary', 'loanwords', 'cultural', 'other', name='articletype'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('last_exported_at', sa.DateTime(), nullable=True),
    sa.Column('exported_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('dialect_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('script_text', sa.Text(), nullable=True),
    sa.Column('romanization', sa.Text(), nullable=False),
    sa.Column('ipa', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=False),
    sa.Column('is_regression_test', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etymology_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('dialect_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('sound_change', 'grammar_change', 'dialect_split', 'contact_event', 'cultural_event', 'lexical_event', 'other', name='eventtype'), nullable=False),
    sa.Column('era_label', sa.String(length=120), nullable=False),
    sa.Column('era_sort_key', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('phonology_rule_id', sa.Integer(), nullable=True),
    sa.Column('grammar_rule_id', sa.Integer(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['etymology_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grammar_rule_id'], ['grammar_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['phonology_rule_id'], ['phonology_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('etymology_events', schema=None) as batch_op:
        batch_op.create_index('ix_etymology_events_article_sort', ['article_id', 'era_sort_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etymology_events', schema=None) as batch_op:
        batch_op.drop_index('ix_etymology_events_article_sort')

    op.drop_table('etymology_events')
    op.drop_table('sample_texts')
    op.drop_table('etymology_articles')
    # ### end Alembic commands ###
