"""InitializeFinalStructure

Revision ID: 6b0cf12c67cc
Revises: 
Create Date: 2026-06-18 00:00:10.795234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0cf12c67cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('native_name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('living', 'extinct', 'liturgical', 'constructed', name='languagestatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_word_order', sa.Enum('SOV', 'SVO', 'VSO', 'VOS', 'OVS', 'OSV', 'free', name='wordorder'), nullable=True),
    sa.Column('morphological_type', sa.Enum('isolating', 'agglutinative', 'fusional', 'polysynthetic', name='morphologicaltype'), nullable=True),
    sa.Column('phonemic_inventory_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('semantic_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_field_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_field_id'], ['semantic_fields.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dialects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('parent_dialect_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geo_tag', sa.Enum('regional', 'class_based', 'archaic', 'pidgin', 'creole', 'liturgical', 'informal', 'other', name='dialecttag'), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('intelligibility_with_parent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_dialect_id'], ['dialects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etymology_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('article_type', sa.Enum('history', 'dialect', 'vocabulary', 'loanwords', 'cultural', 'other', name='articletype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('last_exported_at', sa.DateTime(), nullable=True),
    sa.Column('exported_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inflection_paradigms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_language_id', sa.Integer(), nullable=False),
    sa.Column('target_language_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.Enum('common_ancestor', 'borrowing', 'creole', 'contact', 'constructed_from', name='relationshiptype'), nullable=False),
    sa.Column('era', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_language_id', 'target_language_id', 'relationship_type', name='uq_lang_rel')
    )
    op.create_table('morphemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(length=120), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etymology_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('dialect_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('sound_change', 'grammar_change', 'dialect_split', 'contact_event', 'cultural_event', 'lexical_event', 'other', name='eventtype'), nullable=False),
    sa.Column('era_label', sa.String(length=120), nullable=False),
    sa.Column('era_sort_key', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('etymology_events', schema=None) as batch_op:
        batch_op.create_index('ix_etymology_events_lang_sort', ['language_id', 'era_sort_key'], unique=False)

    op.create_table('grammar_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dialect_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idioms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('dialect_id', sa.Integer(), nullable=True),
    sa.Column('phrase', sa.String(length=512), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idioms', schema=None) as batch_op:
        batch_op.create_index('ix_idioms_language_phrase', ['language_id', 'phrase'], unique=False)

    op.create_table('lexemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('paradigm_id', sa.Integer(), nullable=True),
    sa.Column('lemma', sa.String(length=255), nullable=False),
    sa.Column('gloss', sa.Text(), nullable=True),
    sa.Column('part_of_speech', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paradigm_id'], ['inflection_paradigms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phonology_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dialect_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('dialect_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_regression_test', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('dialect_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('script_type', sa.Enum('alphabet', 'abjad', 'abugida', 'syllabary', 'logographic', 'mixed', 'other', name='scripttype'), nullable=False),
    sa.Column('direction', sa.Enum('ltr', 'rtl', 'ttb', 'boustrophedon', name='scriptdirection'), nullable=False),
    sa.Column('font_face_name', sa.String(length=120), nullable=True),
    sa.Column('font_file_ref', sa.String(length=255), nullable=True),
    sa.Column('orthographic_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('dialect_id', sa.Integer(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('target_text', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'translator', 'imported', name='translationsource'), nullable=False),
    sa.Column('status', sa.Enum('approved', 'draft', 'rejected', name='translationstatus'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translation_memories', schema=None) as batch_op:
        batch_op.create_index('ix_tm_dialect_status', ['dialect_id', 'status'], unique=False)
        batch_op.create_index('ix_tm_language_status', ['language_id', 'status'], unique=False)

    op.create_table('glyphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('meaning', sa.String(length=255), nullable=True),
    sa.Column('unicode_value', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('script_id', 'symbol', name='uq_glyph_symbol')
    )
    op.create_table('senses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lexeme_id', sa.Integer(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lexeme_id', sa.Integer(), nullable=False),
    sa.Column('dialect_id', sa.Integer(), nullable=True),
    sa.Column('written_form', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idiom_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idiom_id', sa.Integer(), nullable=False),
    sa.Column('word_form_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idiom_id'], ['idioms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_form_id'], ['word_forms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pronunciations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_form_id', sa.Integer(), nullable=False),
    sa.Column('ipa', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['word_form_id'], ['word_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sense_semantic_fields',
    sa.Column('sense_id', sa.Integer(), nullable=False),
    sa.Column('semantic_field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['semantic_field_id'], ['semantic_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sense_id'], ['senses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sense_id', 'semantic_field_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sense_semantic_fields')
    op.drop_table('pronunciations')
    op.drop_table('idiom_words')
    op.drop_table('word_forms')
    op.drop_table('senses')
    op.drop_table('glyphs')
    with op.batch_alter_table('translation_memories', schema=None) as batch_op:
        batch_op.drop_index('ix_tm_language_status')
        batch_op.drop_index('ix_tm_dialect_status')

    op.drop_table('translation_memories')
    op.drop_table('scripts')
    op.drop_table('sample_texts')
    op.drop_table('phonology_rules')
    op.drop_table('lexemes')
    with op.batch_alter_table('idioms', schema=None) as batch_op:
        batch_op.drop_index('ix_idioms_language_phrase')

    op.drop_table('idioms')
    op.drop_table('grammar_rules')
    with op.batch_alter_table('etymology_events', schema=None) as batch_op:
        batch_op.drop_index('ix_etymology_events_lang_sort')

    op.drop_table('etymology_events')
    op.drop_table('morphemes')
    op.drop_table('language_relationships')
    op.drop_table('inflection_paradigms')
    op.drop_table('etymology_articles')
    op.drop_table('dialects')
    op.drop_table('semantic_fields')
    op.drop_table('languages')
    # ### end Alembic commands ###
