"""Added Foreign Keys for dialect/language relationships

Revision ID: a01dc4ce3504
Revises: 3533723938bd
Create Date: 2026-06-16 21:13:30.662852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a01dc4ce3504'
down_revision = '3533723938bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_dialect_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_languages_default_dialect", 'dialects', ['default_dialect_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('default_dialect_id')

    # ### end Alembic commands ###
